In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
import joblib

In [ ]:
df= pd.read_csv("/content/Realistic_JEE_Marks_Percentile_Rank_Dataset_v2.csv")

In [ ]:
df.loc[38]

raw_marks                38.000000
approx_percentile        58.000000
approx_rank          504000.000000
normalized_score          0.126667
Name: 38, dtype: float64

In [ ]:
df = df[["raw_marks", "approx_percentile", "approx_rank"]].dropna()

     raw_marks  approx_percentile  approx_rank
0            0            0.50000      1194000
1            1            2.47500      1170300
2            2            4.45000      1146600
3            3            6.42500      1122900
4            4            8.40000      1099200
..         ...                ...          ...
296        296           99.99200           96
297        297           99.99275           87
298        298           99.99350           78
299        299           99.99425           69
300        300           99.99500           60

[301 rows x 3 columns]

In [ ]:
print(df.columns)

Index(['raw_marks', 'approx_percentile', 'approx_rank'], dtype='object')

In [ ]:
X=df[['raw_marks']]
y_percentile=df['approx_percentile']
y_rank=df['approx_rank']

In [ ]:
X_train, X_test, y_train_p, y_test_p = train_test_split(
    X, y_percentile, test_size=0.2, random_state=42
)

# For rank
_, _, y_train_r, y_test_r = train_test_split(
    X, y_rank, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model1=LinearRegression()
model2=DecisionTreeRegressor()
model3= RandomForestRegressor(n_estimators=300, random_state=42)

models = {
    "Linear Regression": model1,
    "Decision Tree": model2,
    "Random Forest": model3
}

# Evaluation loop for Percentile
print("\n=== Percentile Prediction Results ===")

for name, model in models.items():
    model.fit(X_train, y_train_p)
    preds = model.predict(X_test)

    print(f"\nModel: {name}")
    print("MAE:", mean_absolute_error(y_test_p, preds))
    print("MSE:", mean_squared_error(y_test_p, preds))
    print("R2 :", r2_score(y_test_p, preds))

=== Percentile Prediction Results ===

Model: Linear Regression
MAE: 11.17040628958439
MSE: 187.05612598452674
R2 : 0.6327783296872823

Model: Decision Tree
MAE: 0.3391721311475402
MSE: 0.3743500425774137
R2 : 0.9992650898376443

Model: Random Forest
MAE: 0.17970734061931753
MSE: 0.11363239724096687
R2 : 0.999776921079185

In [ ]:
print("\n=== Rank Prediction Results ===")

for name, model in models.items():
    model.fit(X_train, y_train_r)
    preds = model.predict(X_test)

    print(f"\nModel: {name}")
    print("MAE:", mean_absolute_error(y_test_r, preds))
    print("MSE:", mean_squared_error(y_test_r, preds))
    print("R2 :", r2_score(y_test_r, preds))

=== Rank Prediction Results ===

Model: Linear Regression
MAE: 134044.87547501267
MSE: 26936082141.771854
R2 : 0.6327783296872824

Model: Decision Tree
MAE: 4070.065573770492
MSE: 53906406.13114754
R2 : 0.9992650898376443

Model: Random Forest
MAE: 2156.488087431694
MSE: 16363065.202697998
R2 : 0.999776921079185

In [ ]:
print("\n=== Rank Prediction Results ===")

for name, model in models.items():
    model.fit(X_train, y_train_r)
    preds = model.predict(X_test)

    print(f"\nModel: {name}")
    print("MAE:", mean_absolute_error(y_test_r, preds))
    print("MSE:", mean_squared_error(y_test_r, preds))
    print("R2 :", r2_score(y_test_r, preds))

=== Rank Prediction Results ===

Model: Linear Regression
MAE: 134044.87547501267
MSE: 26936082141.771854
R2 : 0.6327783296872824

Model: Decision Tree
MAE: 4070.065573770492
MSE: 53906406.13114754
R2 : 0.9992650898376443

Model: Random Forest
MAE: 2156.488087431694
MSE: 16363065.202697998
R2 : 0.999776921079185

In [ ]:
import joblib

# Save Percentile Model
joblib.dump(models["Random Forest"].fit(X_train, y_train_p), "percentile_model.pkl")

# Save Rank Model
joblib.dump(models["Random Forest"].fit(X_train, y_train_r), "rank_model.pkl")

print("Models saved successfully!")

Models saved successfully!

In [ ]:
import joblib
percentile_model = joblib.load("/content/percentile_model.pkl")
rank_model = joblib.load("/content/rank_model.pkl")

In [ ]:
import pandas as pd

raw_marks = 160
X_input = pd.DataFrame({"raw_marks": [raw_marks]})

predicted_percentile = percentile_model.predict(X_input)[0]
predicted_rank = rank_model.predict(X_input)[0]

print("Predicted Percentile:", predicted_percentile)
print("Predicted Rank:", predicted_rank)

Predicted Percentile: 98.18111666666707
Predicted Rank: 21826.6